name: Build macOS Release Artifacts

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version tag for the release (e.g., v0.1.0)'
        required: true
        type: string

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'hld/go.mod'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install WUI dependencies
        working-directory: humanlayer-wui
        run: bun install

      - name: Build Tauri app (including DMG)
        working-directory: humanlayer-wui
        run: bun run tauri build

      - name: Build daemon for macOS ARM
        working-directory: hld
        run: GOOS=darwin GOARCH=arm64 go build -o hld-darwin-arm64 ./cmd/hld

      - name: Create install instructions
        run: |
          cat > INSTALL.md << 'EOF'
          # HumanLayer macOS Installation Instructions

          ## Prerequisites
          - macOS (Apple Silicon/M-series)
          - Node.js installed

          ## Installation Steps

          1. **Install the WUI Application**
             - Open the downloaded `humanlayer-wui_*.dmg` file
             - Drag the HumanLayer WUI app to your Applications folder
             - Close the DMG window

          2. **Install the Daemon**
             - Download `hld-darwin-arm64`
             - Make it executable: `chmod +x hld-darwin-arm64`
             - Move to your PATH: `sudo mv hld-darwin-arm64 /usr/local/bin/hld`
             - Verify installation: `hld --version`

          3. **Install the CLI**
             ```bash
             npm install -g humanlayer@0.10.0
             ```

          4. **Start Using HumanLayer**
             - Run the daemon: `hld`
             - Launch the WUI from Applications
             - Use the CLI: `humanlayer --help`

          ## Troubleshooting

          If macOS blocks the daemon from running:
          1. Go to System Settings > Privacy & Security
          2. Look for the blocked app message
          3. Click "Allow Anyway"

          For more help, visit: https://docs.humanlayer.dev
          EOF

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: humanlayer-wui-macos-dmg
          path: humanlayer-wui/src-tauri/target/release/bundle/dmg/*.dmg
          if-no-files-found: error

      - name: Upload daemon artifact
        uses: actions/upload-artifact@v4
        with:
          name: hld-darwin-arm64
          path: hld/hld-darwin-arm64
          if-no-files-found: error

      - name: Upload install instructions
        uses: actions/upload-artifact@v4
        with:
          name: INSTALL
          path: INSTALL.md
          if-no-files-found: error

      # Create GitHub Release with artifacts
      - name: Create Release
        if: github.event_name == 'workflow_dispatch'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.release_version }}
          release_name: HumanLayer ${{ github.event.inputs.release_version }} - macOS Release
          body: |
            ## HumanLayer ${{ github.event.inputs.release_version }} - macOS Release

            This release includes:
            - HumanLayer WUI (Desktop Application) - DMG installer
            - HumanLayer Daemon (hld) - ARM64 binary
            - Installation instructions

            ### Installation
            Please download all three files below and follow the instructions in `INSTALL.md`.

            ### Requirements
            - macOS (Apple Silicon/M-series)
            - Node.js for the CLI component
          draft: true
          prerelease: false

      - name: Find DMG file
        if: github.event_name == 'workflow_dispatch'
        id: find_dmg
        run: |
          DMG_PATH=$(find humanlayer-wui/src-tauri/target/release/bundle/dmg -name "*.dmg" | head -1)
          echo "dmg_path=$DMG_PATH" >> $GITHUB_OUTPUT
          echo "dmg_name=$(basename $DMG_PATH)" >> $GITHUB_OUTPUT

      - name: Upload Release Asset - DMG
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.find_dmg.outputs.dmg_path }}
          asset_name: ${{ steps.find_dmg.outputs.dmg_name }}
          asset_content_type: application/x-apple-diskimage

      - name: Upload Release Asset - Daemon
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: hld/hld-darwin-arm64
          asset_name: hld-darwin-arm64
          asset_content_type: application/octet-stream

      - name: Upload Release Asset - Install Instructions
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: INSTALL.md
          asset_name: INSTALL.md
          asset_content_type: text/markdown
